### ISSUE TITLE
IDA Biodiversity Grade Summary (need code)

### ISSUE THREAD

**Issue by mackenzieyoung** [louiscastagliola/intro-data-capstone-biodiversity#1]
### Criteria 1: Presentation / Analysis Document
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ You included all of the requirements in your presentation, but in general, the slides could have been formatted better. For example, your graphs are very difficult to read because they're so small, so it would have been better if they had been on their own slide. Also, you have a lot of words on each slide, and it is always best to have a few words as possible.  
 
### Criteria 2: Code Accuracy
* _Score Level:_ 0 (Code not included)
* _Comment(s):_ You said that you did all of your programming in the Codecademy environment, but you still need to submit it somehow as a .py file, because I can't see that!

#### Edit
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, your code accurately retrieved the data intended, and you accurately calculated Minimum detectable size and Sample size determination. There were a few spots where your code could have been simpler, but it was still done correctly.

### Criteria 3: Understanding hypothesis testing and interpreting the p-value
* _Score Level:_ 2 (Approaches expectations)
* _Comment(s):_ Good, but you would have gotten all 4 points if you had explicitly stated what the null hypothesis was. That is, you say "the null hypothesis was confirmed", but you never say what the null hypothesis is. Also, in general we say that we _fail_ to reject the null hypothesis, not that we _confirm_ it.
 For both the endangerment of species and foot and mouth disease analysis you want to:
1. State the hypothesis
2. Run hypothesis testing and state the results
3. Based on the results accept/reject the hypothesis
4. Interpret the hypothesis outcome and connect to the objective of the analysis

### Criteria 4: Ability to interpret the Objective & Outcome of the analysis in business context
* _Score Level:_ 3 (Meets expectations)
* _Comment(s):_ You do state recommendations in your presentation, but they are very vague. Go a little farther than just saying that conservationists should focus their efforts on species that are at risk of becoming endangered (e.g., say what those species are).
 
### Overall Score: 13/16
Good job overall! Your presentation was a good start, but would have been better if your slides had fewer words and bigger plots, and if you gave a little more information about your hypotheses and recommendations. The analyses themselves look to be correct.

**Comment by louiscastagliola** [comment]
Code Uploaded to main branch.
